### ISSUE TITLE
Add language menu (FR/EN)

### ISSUE THREAD

**Issue by Asam237** [osscameroon/onacut#110]
Add here..
![add_langues](https://user-images.githubusercontent.com/34966088/181208805-d0e2c45b-f787-45fb-ba50-48c600ecea6d.png)

Like this..
![commececi](https://user-images.githubusercontent.com/34966088/181770744-3ae67349-b728-42bf-b79e-fa785cd31e5e.png)

**Comment by godsakani** [comment]
> 

Hello @Asam237 am i adding in the site nav?

**Comment by Asam237** [comment]
Yes !
