### ISSUE TITLE
Retrieve all alerts from the backend on the Map level (on the StreetMap.page.tsx file)

### ISSUE THREAD

**Issue by Asam237** [osscameroon/onacut#119]
- [ ] Remove constants at the file level (LIST_VILLE, LIST_QUARTIER)
- [ ] Recovering alerts from the backend
- [ ] Display alerts: For the moment we display the alerts taken as a marker of a region. The alert is an object that contains: the name of the region, the number of alerts of this region, the point (longitude and latitude)

**Comment by yokwejuste** [comment]
Hello @Asam237 I'm a bit confused concerning this issue. What is required from me? Because we have the alerts displayed already at the frontend. Please, can you help me clear my doubts?

**Comment by Asam237** [comment]
@yokwejuste , There is a constant file in (scripts/list_ville.ts), however, we do not want to use this file anymore and we would like to receive this information from the backend !

**Comment by yokwejuste** [comment]
Better now! I'll like to know what you'll suggest to me to do that data retrieval .
