### ISSUE TITLE
Implement the button FR / EN

### ISSUE THREAD

**Issue by Asam237** [osscameroon/onacut#123]
You can use this tutorial as a basis =>  https://www.youtube.com/watch?v=JVy6-9bgqgU

**Comment by godsakani** [comment]
Ok Sir Thank You

**Comment by godsakani** [comment]
Hello @Asam237  i saw this Library i don't know if is ok i used it. Is call i18next

**Comment by Asam237** [comment]
@godsakani  Yes, you can use this library and just follow the procedure in the tutorial !

**Comment by godsakani** [comment]
> @godsakani Yes, you can use this library and just follow the procedure in the tutorial !

Ok @Asam237  thank you I had to do more research to get the simplest method. Currently am out of power when it return will work on it

**Comment by Asam237** [comment]
implement here => #142
