### ISSUE TITLE
Missing asset import

### ISSUE THREAD

**Issue by mouafus** [osscameroon/onacut#140]
I tried to launch the project with docker in "run docker-compose", when building the frontend, there is this error 
`#0 38.79 /app/src/assets/data/Items.data.ts`
`#0 38.79 TypeScript error in /app/src/assets/data/Items.data.ts(24,15):`
`#0 38.79 Cannot find name 'report'.  TS2304`
`#0 38.79 `
`#0 38.79     22 |     },`
`#0 38.79     23 |     {`
`#0 38.79   > 24 |         icon: report,`
`#0 38.79        |               ^`
`#0 38.79     25 |         name: LANGUAGE.home.signalerPanne,`
`#0 38.79     26 |         link: "/add-alert",`
`#0 38.79     27 |     },`

It is a missing file, it has surely not been committed .

**Comment by Asam237** [comment]
implement here #142
