### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by Asam237** [osscameroon/onacut#143]
add a pagination to the city list:

https://user-images.githubusercontent.com/34966088/196007496-889dbb39-0830-4ba4-89af-157a0e73bc5c.mp4

like this:

![Screenshot from 2022-10-15 22-05-55](https://user-images.githubusercontent.com/34966088/196007575-430d2303-13a9-4b81-8b7e-8d78efc9b057.png)

**Comment by mouafus** [comment]
I'm in

**Comment by mouafus** [comment]
@Asam237 i think the best wait to paginate call and API endpoint with the page and the per_page. Is not a good idea to make the pagination with  all data in front
