### ISSUE TITLE
fix the frontend CI

### ISSUE THREAD

**Issue by Sanix-Darker** [osscameroon/onacut#148]
For the front-end CI to be fixed, this value should be probably updated : https://github.com/osscameroon/onacut/blob/main/.github/workflows/frontend-stage-deploy.yaml#L21 

12 -> 14 (or the LTS version number)

@Asam237 @Zaker237 

PS: not tested yet !

**Comment by Sanix-Darker** [comment]
doing that change seems to require updates on the codebase ... 
![Screenshot from 2022-10-23 20-59-32](https://user-images.githubusercontent.com/22576758/197410579-aabdf732-1227-4bdd-b90f-3d4d01604b30.png)

**Comment by Asam237** [comment]
@mouafus please take this with you to the refractor

**Comment by mouafus** [comment]
Ok. I will fix it

**Comment by Zaker237** [comment]
Hallo @mouafus did you allready fix it?
i got the following error on my merge
![Screenshot from 2022-11-29 07-34-56](https://user-images.githubusercontent.com/49993443/204456496-9325b616-524b-4c92-8754-9d768c596a39.png)

**Comment by mouafus** [comment]
I don't know why you have this !
I will make a test today. i don't have it.

**Comment by Zaker237** [comment]
> I don't know why you have this ! I will make a test today. i don't have it.

i'm not getting it local but in the github action that build the frontend

**Comment by mouafus** [comment]
> > I don't know why you have this ! I will make a test today. i don't have it.
> 
> i'm not getting it local but in the github action that build the frontend

AH, don't worry, it already fixed
