### ISSUE TITLE
Display the number of alerts per region on the list

### ISSUE THREAD

**Issue by Asam237** [osscameroon/onacut#96]
Like this

![nag](https://user-images.githubusercontent.com/34966088/176118854-ec7dce99-e71a-4789-90f5-68080e798d4e.png)

**Comment by yokwejuste** [comment]
@Asam237, @Zaker237 For this particular task. This number display should be at the level of the regions I guess. Please I'll need better description for this.

**Comment by yokwejuste** [comment]
Is it something that looks like this?
![image](https://user-images.githubusercontent.com/71908316/178189143-dfec9eca-3e27-420b-8c05-b5eb8c20326f.png)
Please don't mind my screenshot I'm still trying to identify the code work using default values before switching to variables.
