### ISSUE TITLE
Add the show on map button to see the position on the map

### ISSUE THREAD

**Issue by Asam237** [osscameroon/onacut#97]
Like this

![gaa](https://user-images.githubusercontent.com/34966088/176120655-d3343da6-8a45-4c0c-8252-3c224f438c6f.png)

**Comment by Asam237** [comment]
@godsakani , In the list of alert zones, add a button that will redirect us to the map view !

https://user-images.githubusercontent.com/34966088/176230436-e112c70a-e760-4bdb-b166-fdf83e594283.mp4


![lv](https://user-images.githubusercontent.com/34966088/176230535-6d9aa6f6-c0dd-487b-a948-d2ba27838ff9.png)

**Comment by godsakani** [comment]
> @godsakani , In the list of alert zones, add a button that will redirect us to the map view !
> 
>  simplescreenrecorder-2022-06-28_17.17.43.mp4 
> ![lv](https://user-images.githubusercontent.com/34966088/176230535-6d9aa6f6-c0dd-487b-a948-d2ba27838ff9.png)

Ok thank you for this

**Comment by godsakani** [comment]
> Like this
> 
> ![gaa](https://user-images.githubusercontent.com/34966088/176120655-d3343da6-8a45-4c0c-8252-3c224f438c6f.png)

Hello @Asam237, @Sanix-Darker I wish to ask if I should create a new button component here?

**Comment by Sanix-Darker** [comment]
You can do that or add a normal customized button like it has been done here : https://github.com/osscameroon/onacut/blob/main/frontend/src/components/search/Search.component.tsx#L19 @godsakani , it's up to you....

**Comment by godsakani** [comment]
> You can do that or add a normal customized button like it has been done here : https://github.com/osscameroon/onacut/blob/main/frontend/src/components/search/Search.component.tsx#L19 @godsakani , it's up to you....

Ok Thank you

**Comment by Asam237** [comment]
When you do a console log on the details page, you have this

![details_god](https://user-images.githubusercontent.com/34966088/178197281-42292839-68f3-47c2-a5e5-47075bf12808.png)

So, by implementing the button, you redirect to the map (StreetMap) with the coordinates(lattitude, longitude).

**Comment by godsakani** [comment]
> When you do a console log on the details page, you have this
> 
> ![details_god](https://user-images.githubusercontent.com/34966088/178197281-42292839-68f3-47c2-a5e5-47075bf12808.png)
> 
> So, by implementing the button, you redirect to the map (StreetMap) with the coordinates(lattitude, longitude).
Hello @Asam237 am i to console log this in the details or citydetails page
